### ISSUE TITLE
logic and function change for Garage door controller ZW062

### ISSUE THREAD

**Issue by ndit-dev** [athombv/com.aeotec#106]
Hi,

[-1-] The Logic is reveresed for "locked/unlocked" state
The Garage door controller ZW062 seems to have reversed locked/unlocked logic, which [@yhaugo](https://github.com/yhaugom). already tried to adress with [this pull request](https://github.com/athombv/com.aeotec/pull/86#pullrequestreview-90594572). But this request got stuck and never implemented. This is needed.

[-2-] The class and mobile card is not really right for this driver
This is how the device shows up in homey. [https://i.imgur.com/LTC0jFI.png](https://i.imgur.com/LTC0jFI.png).
The toggle switch is both the button to change the state of the door AND the representation of the tilt-sensor. I think these should be separated, one button to toggle the door to open/close. And one state to show if the door is opened or closed (locked or unlocked, since it is represented as a lock, not a door)

Best of all, would of course be if there where a class for doors, since this is not really a lock, but it's the closes class there is i guess

**Comment by yhaugom** [comment]
Started on this a few days ago. I was asked to change my pull request to implement a setting value to switch the logic for existing garage door controllers. 
Problem is the developer CLI had been updated and it is doing more thoroughly checks, and I can't test my change without fixing all the errors in the JSON-file that is already there. Not to my knowledge anyway. 
Have some trouble understanding how the app can differ between allready installed devices and devices about to be paired, since I need to do that too not break the logic in people's flows. Do I need to create a device.js in addition to the driver.js?
Can't seem to wrap my head around this.

**Comment by yhaugom** [comment]
To clarify; I started fixing errors in the JSON-file but it is a lot of them. I really don't understand why it triggers on some of them. Thought only strings had to have double quotation marks in JSON. And it is not in my part of the code. It's all over the JSON-file. I'm confused...

**Comment by RobinBol** [comment]
Moved issue to main issue tracker: https://github.com/athombv/homey/issues/2568
