### ISSUE TITLE
Support for Aeotec, Home energy Meter Gen5 - Three clamps 60A 

### ISSUE THREAD

**Issue by kfcarlsson** [athombv/com.aeotec#115]
Hi,

First I am sorry if I am writing this at the wrong place. Please advise where to write.

I have installed Aeotec, Home energy Meter Gen5 - Three clamps 60A together with my Homey but I haven't come so long. I have only the connection to Homey and it says it is:
Device Class (Basic)          BASIC_TYPE_ROUTING_SLAVE
Device Class (Generic)     GENERIC_TYPE_METER
Device Class (Specific)     SPECIFIC_TYPE_SIMPLE_METER

I haven't done any configuration of Associations (Group 1=1) or Parameters (Value=-Empty-) is set.

Actually I do not know where to start??????

I would like to get the used kWH per day or something similar in a graph. 

Any ideas of how to start?

Thanks in advance!

**Comment by RobinBol** [comment]
Thank you for reporting your issue, we do not monitor these app repositories, you could report your issue here: https://github.com/athombv/homey/issues.

However, support for the Home Energy Meter is not yet complete, there are some know issues (https://github.com/athombv/homey/issues/2578), therefore I will just close this issue. You can monitor progress via the issue I referenced.
