### ISSUE TITLE
Smart switch 6 - minimum watt change for update not working

### ISSUE THREAD

**Issue by gruijter** [athombv/com.aeotec#48]
My smart switch 6 is sending an enormous amount of updates to Homey due to very small watt changes (0.01 watt). Setting a minimum report watts in the settings does not have any effect. I tried values between 1 and 10.000 in settings.

**Comment by RobinBol** [comment]
Did you try both parameter 91 ("Minimum wattage change needed before an update report is send") and 92("Minimum wattage change (%) needed before an update report is send")? They might interfere with each other.

The default value for parameter 91 is 25W I don't expect this parameter to cause the large amount of `COMMAND_CLASS_METER` reports, however parameter 92 has a default value of 5% which is know to cause many reports due to fluctuating power usage. In the latest Aeotec app update we have set the default value to 30% (this will be applied after a re-pair).

**Comment by gruijter** [comment]
In my settings screen I have no parameters called 91 or 92... I only have 'Minimale verandering in wattage nodig voor het verzenden van een update'

**Comment by RobinBol** [comment]
That is why I added the English translations:) If you have paired the device with an up-to-date app version you'll have:
- Minimale verandering in wattage nodig voor het verzenden van een update
and
- Minimale verandering in wattage (%) nodig voor het verzenden van een update

If not, re-pairing the device will add the settings and will probably solve your problem.

**Comment by gruijter** [comment]
Ok, think I need to re-pair then.

**Comment by RobinBol** [comment]
If this didn't solve your problem, please re-open this issue!
