### ISSUE TITLE
Support for LED Strip (ZW121)

### ISSUE THREAD

**Issue by mtudor** [athombv/com.aeotec#73]
Is anyone working on support for the Aeotec LED strip?  If not I could probably give it a go (though limited time means it might take a while) but thought I'd better ask first!

Cheers,

Mark.

**Comment by RobinBol** [comment]
Athom is not currently working on support for the LED strip. So please, go ahead:)

**Comment by jprgomet** [comment]
do it, please .. I don't see any better led strips z-wave compatible ..

**Comment by jprgomet** [comment]
There is an opinnion https://forum.athom.com/discussion/comment/62640/#Comment_62640
that strip is very similar to bulb (has RGB + warm + cold white) in terms of hw and funcionality, so maybe some copy/paste could work :)

**Comment by jprgomet** [comment]
cannot be added as bulb .. included as generic .. this is what I got .. 

<img width="530" alt="screen shot 2017-12-31 at 23 17 23" src="https://user-images.githubusercontent.com/5060994/34464475-12452ab6-ee81-11e7-9bfd-0cccd0550a15.png">

**Comment by jprgomet** [comment]
LED strip is in the kitchen .. and wife is not happy .. you all know what that means .. I gotta do something .. and better do it fast :)

I don't know what I am doing .. never done this before

I installed github desktop for mac .. forked master .. found ZW098 .. bulb files .. made duplicates .. and now changing what I see fit to change in local files .. most of parameters are the same according to aeotec documentation .. so when I am done editing files I will need help how to install it / test it on my homey?

**Comment by yhaugom** [comment]
To install and test the app with your driver on Homey is pretty straight forward actually.

All the steps are described very well at https://apps.developer.athom.com/tutorial-Getting%20Started.html
You need Node.js if you dont have it: https://nodejs.org/en/download/

Then do step two and three in the Getting Started page ('npm install -g athom-cli’, and ‘athom login’ in terminal).
You dont need to create a project since you already have that cloned to your computer, so you can skip step 4.

Then you just go to the folder of the cloned repository and run 'athom project --run’ to test your version, or athom project --install’ if you want it to be persistent between reboots of your homey.

Note that the version installed will be replaced by your app, but it shouldn’t break anything when reinstalling the master branch version from app store again. You should just be aware of it. I guess you could try to change the id of the app to something else to try to avoid this, but don’t know if that is a good idea. Might be conflicts between the two apps? I am new to this as well.
Good luck.

Yngve

**Comment by jprgomet** [comment]
tnx .. was reading Getting started .. but did not tried it .. will try .. we are going on ski vacation for 7 days .. so I will not be able to experiment much if any .. 

I have just one Aeotec device LED strip .. so having my app replacing original will not make much damage :)

**Comment by jprgomet** [comment]
did it all .. paired with my app .. its alive! .. I am so thrilled and happy .. it works! .. will tweak it some more .. but can on/off .. change collors .. dimm .. all that I need at the moment :) wohooooo

**Comment by jprgomet** [comment]
@RobinBol made PR .. please assist .. I am super new to this .. thank you

**Comment by andydp84** [comment]
Anyone following up on this? Would be great if the LED strip is supported...

**Comment by MatthewWaanders** [comment]
Hey guys!

I'm a bit late to the party but I'm able to make you all a bit happier today. The LED strip will be supported in the Aeotec app after the SDK2 rewrite!

**Comment by RobinBol** [comment]
Moved issue to main issue tracker: https://github.com/athombv/homey/issues/2575
