### ISSUE TITLE
Support for Aeotec Wallmote Dual

### ISSUE THREAD

**Issue by nwaarbroek** [athombv/com.aeotec#89]
At this moment Wallmote Quad is supported. Since september last year a new version is released with only 2 buttons. Currently the Homey doesn't recognise the 2 button version.

Is it possible to add support for the dual version?

**Comment by idarlund** [comment]
Any updates on this one?
The tecnical manual can be found [here](https://www.tronika.no/en/index.php?controller=attachment&id_attachment=600)

**Comment by rabell79** [comment]
Any feedback on whether this is likely to be added?

**Comment by Veldkornet** [comment]
I just purchased a Wallmote Dual (assuming it was supported since the Quad is supported).
I see this request has been open for a while.... Any news as to when it will be added? Do you need any more information that I can give?

Fabrikant ID: 134
Product Type ID: 2
Product ID: 129

![image](https://user-images.githubusercontent.com/10297361/40534994-1c8ca604-6008-11e8-8caa-796bf9f7f808.png)

**Comment by MatthewWaanders** [comment]
Hey @Veldkornet and @rabell79,

Wallmote dual compatibility is indeed coming to the Aeotec app! It will take a while as it's part of a bigger overhaul, but you can rest assured it's going to be added!

**Comment by RobinBol** [comment]
Moved issue to main issue tracker: https://github.com/athombv/homey/issues/2571
